package.json, src/app/(rootLayout)/(home)/page.tsx, src/components/atoms/button.tsx, src/lib/utils.ts, yarn.lock
작업내용
tailwind를 활용하여 재사용 가능한 button component 완성
=> #3 UI(button Design): 재사용가능한 button component 완성

src/components/atoms/selectContainer.tsx, src/components/organisms/selectBox.tsx, src/components/pages/signupModal.tsx
- selectBox Container에 추가 className 설정 할 수 있게 변경
- none
=> UI(selectBox):selectBox Container에 추가 className 설정 할 수 있게 변경

.vscode/settings.json, src/app/(rootLayout)/(home)/page.tsx, src/app/(rootLayout)/modal/page.tsx, src/app/layout.tsx, src/components/molecules/signupHeader.tsx, src/components/pages/signupModal.tsx, src/components/pages/signupTest.tsx, src/context/modalContext.tsx, src/provider/compoundProvider.tsx
context api로 modal 구현
- context api 로 작성한 이유: redux는 순수함수로 작성되어야하는데 modal 로직은 component를 인자로 넘겨주는 방식임으로 redux와 어울리지않아 context api로 작성
- home page에서 test할 수 있게 데모 ui 작성
=> feat(signup): Modal

src/api/postApi.ts, src/components/organisms/tagContainer.tsx, src/context/tag.context.tsx
- tag Component에 api 연결 추가
- tag DB에 tag가 있는 이름이면 DB에 추가되지 않음
- 반대로 tag가 없으면 tag를 작성하고 enter or ','를 입력했을때 자동 등록
-
=> feat(tagComponent):

src/app/(rootLayout)/uiComponents/page.tsx, src/components/molecules/dateRangePicker.tsx
기간선택 가능한 data picker component
=> UI & feat:

src/app/api/notion/database/route.ts, src/app/api/notion/webShare/route.ts, src/components/molecules/post/postInputContainer.tsx
- notion link
- 유효성 검사 버튼 label 변경
- 유효성 실패시 출력 text 변경
=> fix: notion link 관련 text 변경

src/api/postApi.ts, src/components/atoms/modal.tsx, src/components/molecules/post/postInfoContainer.tsx, src/components/molecules/post/tutorContainer.tsx, src/components/pages/progressModal.tsx, src/hooks/usePostWriteForm.tsx, src/types/posts.types.ts, src/validators/posts/posts.validator.ts
=> feat:게시물 api 연결

src/components/atoms/uploadThumbnailText.tsx, src/components/molecules/post/thumbnailContainer.tsx, src/components/organisms/postFormContainer.tsx, src/hooks/usePostWriteForm.tsx, src/validators/posts/posts.validator.ts, tailwind.config.ts
=> UI: 게시물 등록에 기본이미지 등록

src/api/authApi.ts, src/app/(rootLayout)/(backofficeLayout)/(home)/page.tsx, src/app/(rootLayout)/role/result/page.tsx, src/app/api/auth/lastConnectRole/route.ts, src/app/api/auth/login/route.ts, src/components/atoms/menubarLogout.tsx, src/components/pages/roleResult/roleResult.tsx, src/components/pages/signIn.tsx, src/types/auth.types.ts, src/utils/auth.server.util.ts, src/utils/auth.util.ts, src/utils/serverAPI.ts, src/utils/utils.ts
=> feat : 마지막 권한 조회되었을 때 정보 cookie 저장

src/api/authApi.ts, src/app/(rootLayout)/role/result/page.tsx, src/components/pages/roleResult/roleWait.tsx, src/components/pages/signIn.tsx, src/utils/auth.util.ts, src/utils/clientAPI.ts
=> fix: 권한 승인 후 거부 시 오류 수정

src/app/api/notion/content/route.ts, src/app/layout.tsx, src/components/atoms/tagInput.tsx, src/components/atoms/uploadThumbnailText.tsx, src/components/molecules/post/uploadContainer.tsx, src/components/molecules/signupHeader.tsx, src/components/organisms/backOfficeMenuBar.tsx, src/components/organisms/tagContainer.tsx, src/components/pages/signIn.tsx, src/components/pages/signUpCompleteModal.tsx, src/components/ui/button.tsx, src/components/ui/buttonVariants.ts, src/context/modal.context.tsx, src/context/tag.context.tsx, src/context/useModalContext.ts, src/context/useTagContext.ts, src/hooks/usePostWriteForm.tsx, src/hooks/useSignupForm.tsx
프론트 배포 오류 수정
```tsx
1. ./src/app/api/notion/content/route.ts 파일:
불필요한 이스케이프 문자 (/)가 있습니다. 슬래시 앞의 백슬래시를 제거해주세요.
2. ./src/app/layout.tsx 파일:
컴포넌트 외에 다른 것도 내보내고 있습니다. 상수나 함수를 별도의 파일로 옮겨 Fast Refresh를 활성화하세요.
3. ./src/components/atoms/uploadThumbnailText.tsx 파일:
CSS 클래스 순서에 문제가 있습니다. 다음과 같이 수정하세요:
tsxCopyclassName="absolute inset-0 bg-image-black"
4. ./src/components/molecules/post/uploadContainer.tsx 파일:
handleUrlChange 함수가 정의되었지만 사용되지 않고 있습니다. 사용하거나 제거하세요.
5. ./src/components/organisms/backOfficeMenuBar.tsx 파일:
value 변수가 정의되었지만 사용되지 않고 있습니다. 사용하거나 제거하세요.
6. ./src/components/ui/button.tsx 파일:
2번과 유사하게, 컴포넌트 외의 것을 내보내고 있습니다. 컴포넌트가 아닌 내보내기를 별도 파일로 옮기세요.
7. ./src/context/modal.context.tsx와 ./src/context/tag.context.tsx 파일:
이 파일들도 컴포넌트 외의 것을 내보내고 있습니다. 컴포넌트가 아닌 내보내기를 별도 파일로 옮기세요.
```
혹시몰라서 기존 …
=> [#70] Fix : 백엔드 배포 오류 수정작업

.github/workflows/cicd-prod.yml
=> [#67] CICD: cicd-prod 변경

.github/workflows/ci-dev.yml, .github/workflows/ci-prod.yml, .github/workflows/cicd-dev.yml, .github/workflows/cicd-prod.yml
=> refactor(CICD): CI 성능개선

.dockerignore, .github/workflows/ci-dev.yml, .github/workflows/ci-prod.yml, .github/workflows/cicd-dev.yml, .github/workflows/cicd-prod.yml, Dockerfile
=> [#87] refactor: CICD 성능개선

.github/workflows/cicd-dev.yml, .github/workflows/cicd-prod.yml
=> [#87] refactor: CICD 성능개선

.github/workflows/cicd-prod.yml
=> [#98] refactor: cicd 수정

src/components/molecules/postDetail/postDetailTag.tsx, src/components/organisms/postFormContainer.tsx
=> fix: preview tag ui 변경

src/api/client/authApi.ts, src/app/(rootLayout)/(backofficeLayout)/admin/page.tsx, src/components/atoms/authTimer.tsx, src/components/atoms/category/tapMenu.tsx, src/components/atoms/selectInput.tsx, src/components/molecules/form/PhoneField.tsx, src/components/molecules/menuLinkCard.tsx, src/components/organisms/profileChangeForm.tsx, src/components/pages/signIn.tsx, src/components/pages/signupModal.tsx, src/hooks/useSignupForm.tsx, src/types/admin.types.ts, src/validators/auth/login.validator.ts, src/validators/auth/signup.validator.ts
=> [#105] feat : 헬퍼테스트 및 버그 해결

.github/workflows/cicd-dev.yml
=> [#115] refactor: CICD 수정

src/components/atoms/category/postList.tsx
post list 에서 데이터가 없을때 보여줄 페이지 작성
=> feat/ui: post 데이터 없을때 보여줄 페이지 작성 - empty page 작성 - 게시물 작성하기 button 작성

.github/workflows/cicd-dev.yml, .github/workflows/cicd-prod.yml
=> [#122] refactor: cicd 변경

src/app/(rootLayout)/(backofficeLayout)/(home)/page.tsx, src/components/atoms/authTimer.tsx, src/components/atoms/category/adminSelectBoxCategory.tsx, src/middleware.ts, src/utils/clientAPI.ts, src/utils/nextOptions/nextAuth.util.ts
=> fix: /로 접속시 /admin으로 이동시키는 로직 추가

src/components/atoms/button.tsx, src/components/atoms/category/postFilterCategory.tsx, src/components/atoms/category/postIsOpenDropDown.tsx, src/components/atoms/category/postIsOpenSelectBoxCategory.tsx, src/components/atoms/category/postTapMenu.tsx, src/components/atoms/dropDownItem.tsx, src/components/atoms/postsTableRow.tsx, src/components/atoms/refreshButton.tsx, src/components/atoms/searchBar.tsx, src/components/atoms/selectInput.tsx, src/components/atoms/tutorInput.tsx, src/components/atoms/uploadInput.tsx, src/components/molecules/calendar.tsx, src/components/molecules/dateRangePicker.tsx, src/components/molecules/post/postInfoContainer.tsx, src/components/molecules/post/thumbnailContainer.tsx, src/components/molecules/tutorCard.tsx, src/components/organisms/postFormContainer.tsx, src/components/organisms/preview/previewContainer.tsx, src/components/organisms/selectFormBox.tsx, src/components/organisms/tagContainer.tsx, src/components/pages/postDetail/postDetail.tsx, src/components/pages/postListPage.tsx, src/hooks/usePostWriteForm.tsx, src/styles/tagInput.module.css
=> Fix/post previewer UI

src/components/atoms/InputContainer.tsx, src/components/atoms/PasswordContainer.tsx, src/components/molecules/form/PhoneField.tsx, src/components/organisms/acceptTermsGroup.tsx, src/components/organisms/selectFormBox.tsx, src/components/pages/signUpCompleteModal.tsx, src/components/pages/signupModal.tsx, src/utils/utils.ts, src/validators/auth/signup.validator.ts
=> fix: 회원가입, 모달 QA 요청 반영

src/app/(rootLayout)/(backofficeLayout)/admin/page.tsx
=> [#143]fix : 카테고리 undefinded 오류 해결

src/app/(rootLayout)/(backofficeLayout)/admin/page.tsx, src/components/atoms/category/adminSelectBoxCategory.tsx
=> [#145]chore : 권한 승인/거절 단 건 선택 시 영역 수정

src/components/atoms/selectItem.tsx, src/components/atoms/tutorInput.tsx, src/components/molecules/post/tutorContainer.tsx, src/components/molecules/tutorCard.tsx
게시물 작성시 tutor 입력 부분을 선택으로 변경
tutor 선택시 dropdown을 바로 닫히지 않는건 차후 복수 선택편의 성을위해 설정해두었음.
- 차후 복수 선택 가능하게 변경
=> update: 게시물 작성시 tutor 입력 부분을 선택으로 변경

src/hooks/usePostWriteForm.tsx
=> update: 게시물 작성

src/components/atoms/tutorInput.tsx, src/components/molecules/post/postInfoContainer.tsx, src/components/molecules/post/tutorContainer.tsx, src/hooks/usePostWriteForm.tsx, src/validators/posts/posts.validator.ts
- 필드가 전부 입력되지 않았는데 게시하기 버튼이 활성되거나 필드가 채워졌는데 버튼이 비활성화되는 버그 수정
=> fix: 게시물 작성, 게시물 수정 

src/components/molecules/post/postInfoContainer.tsx, src/components/molecules/post/tutorContainer.tsx, src/hooks/usePostWriteForm.tsx
=> fix: 게시물 작성 유효성검사 fix

src/utils/notion/notion.content.util.ts, src/validators/posts/posts.validator.ts
=> update: notion content 속도 개선

src/api/admin/useMutation.ts, src/api/client/authApi.ts, src/api/profile/profileApi.ts, src/class/signup.ts, src/components/pages/profile/phoneChangeModal.tsx, src/components/pages/signIn.tsx, src/components/pages/signupModal.tsx, src/hooks/useSignupForm.tsx, src/validators/auth/signup.validator.ts
=> [#165]Feat : 닉네임 백엔드에서 자동생성으로 회원가입 로직 수정 

src/api/client/postApi.ts, src/components/atoms/category/postTableHeader.tsx, src/components/atoms/postsTableRow.tsx, src/hooks/usePostWriteForm.tsx
게시물 등록 중 notion url이 오류날 경우 무한 로딩 되던 부분 개선
=> [#169] fix: 게시물 등록 중 notion url이 오류날 경우 무한 로딩 되던 부분 개선

src/components/atoms/category/AuthCategory.tsx, src/components/atoms/category/adminSelectBoxCategory.tsx, src/components/atoms/category/categoryContainer.tsx, src/components/atoms/category/postFilterCategory.tsx, src/components/atoms/category/postIsOpenSelectBoxCategory.tsx, src/components/atoms/category/postIsOpenSelectBoxContainer.tsx
dropdown에서 focus가 out되면 닫히게 변경
=> [#167] fix: dropdown focus out close

src/context/tag.context.tsx, src/hooks/usePostWriteForm.tsx
=> fix: tags validation 적용

src/app/(rootLayout)/(backofficeLayout)/admin/page.tsx, src/components/atoms/category/AuthCategory.tsx, src/components/molecules/form/PhonChangeField.tsx, src/components/molecules/form/PhoneField.tsx, src/components/pages/profile/phoneChangeModal.tsx, src/hooks/useSignupForm.tsx
=> [#175] Fix : map key 오류 수정

src/components/molecules/post/postInputContainer.tsx, src/validators/posts/posts.validator.ts
=> [#178] Fix/post max title

src/components/organisms/postFormContainer.tsx, src/hooks/usePageLeaveConfirm.tsx, src/hooks/usePostWriteForm.tsx
게시물 작성, 수정 시 입력 하거나 변한 부분이 있을때 새로고침, 뒤로가기, 다른페이지 이동 기본적으로 막고 confirm 출력
=> [#180] feat: 게시물 작성, 게시물 수정시 입력이 되면 뒤로가기, 새로고침, 다른 페이지 이동 confirm 출력

src/components/molecules/post/postInputContainer.tsx, src/validators/posts/posts.validator.ts
=> fix: 제목 50자로 제한 변경

src/app/(rootLayout)/(backofficeLayout)/admin/page.tsx, src/components/atoms/category/adminSelectBoxCategory.tsx, src/components/molecules/form/PhonChangeField.tsx, src/components/molecules/form/PhoneField.tsx, src/hooks/usePageLeaveConfirm.tsx
유저테스트 피드백 반영
게시물 작성/수정 페이지는 경열님이 적어주신 선에서 피그마를 참고해 모달 문구를 최대한 통일 해봤습니다!
=> [#184] Fix : 유저테스트 피드백 반영

src/components/molecules/form/PhonChangeField.tsx, src/components/molecules/form/PhoneField.tsx
=> [#186]update : 휴대폰 번호 길이 수정

src/components/atoms/category/postList.tsx, src/components/atoms/permissionBoard.tsx, src/components/organisms/postFormContainer.tsx, src/hooks/usePageLeaveConfirm.tsx, src/hooks/usePostWriteForm.tsx
게시물 등록 submit일때는 confirm 건너뛰게 변경
=> fix: 게시물 등록 submit일때는 confirm 건너뛰게 변경

src/api/client/postApi.ts, src/app/(rootLayout)/(backofficeLayout)/admin/page.tsx, src/components/molecules/post/postInputContainer.tsx, src/components/organisms/postFormContainer.tsx, src/components/pages/admin/AuthFilteredList.tsx, src/context/tag.context.tsx, src/hooks/usePageLeaveConfirm.tsx, src/hooks/usePostWriteForm.tsx
=> [#191] Update/post create updated

src/app/(rootLayout)/(backofficeLayout)/posts/[id]/page.tsx, src/app/actions/serverActions.ts, src/hooks/usePostWriteForm.tsx, src/types/posts.types.ts
=> fix: 게시물 등록, 수정 후 route cache 무력화

src/components/atoms/inquiryButton.tsx, src/components/pages/roleResult/roleWait.tsx, src/constants/helpLink.constant.ts
=> feat : 문의하기 연결

src/app/(rootLayout)/(backofficeLayout)/admin/page.tsx, src/components/atoms/InputContainer.tsx, src/components/atoms/PasswordContainer.tsx, src/components/atoms/category/adminSelectBoxCategory.tsx, src/components/molecules/form/PhonChangeField.tsx, src/components/pages/profile/passwordChangeModal.tsx, src/components/pages/profile/phoneChangeModal.tsx
=> [#196] feat : 프로필 변경 페이지 엔터 막기

src/context/tag.context.tsx
=> fix: tag 등록시 공백은 등록못하게 변경

src/validators/auth/login.validator.ts
=> [#202] fix: login password 정규식 적용

src/components/atoms/postsTableRow.tsx
=> [#200] update: 게시물 리스트에서 썸네일 클릭시 디테일 페이지로 이동

src/components/molecules/post/postInputContainer.tsx, src/components/molecules/post/tutorContainer.tsx, src/components/molecules/tutorCard.tsx
=> [#198] update: 게시물 등록 tutor text style 변경

src/context/tag.context.tsx
=> 210 tag작성시 제거

src/components/atoms/category/postFilterCategory.tsx, src/components/pages/postListPage.tsx
=> [#215]fix: 게시물 리스트에서 각 filter 오류 수정

src/api/client/postApi.ts, src/components/atoms/postsTableRow.tsx
=> [#214]fix: notion 최신화 오류로 api url 변경

src/components/atoms/category/tapMenu.tsx, src/components/molecules/form/PhonChangeField.tsx, src/components/pages/profile/roleChangeModal.tsx
=> [#217] Fix : 시연 전 오류수정 작업

src/components/molecules/menuLinkCard.tsx, src/components/organisms/backOfficeMenuBar.tsx, src/components/pages/postListPage.tsx
=> [#219]fix: 게시물 리스트 필터 초기화 등

src/components/atoms/category/AuthCategory.tsx, src/components/atoms/category/postFilterCategory.tsx, src/components/pages/admin/categoryFiltered.tsx
=> [#222] Fix : 카테고리 선택 활성화 오류 수정
